import type { Metric, ReportSection, StrategyReport } from "./types";

const metrics = (...items: Array<[string, string, "Low" | "Medium" | "High", string]>): Metric[] =>
  items.map(([label, value, confidence, note]) => ({ label, value, confidence, note }));

const sections: ReportSection[] = [
  {
    id: "performance",
    shortLabel: "Performance",
    title: "Performance & Repeatability",
    question: "How strong and repeatable is the result?",
    conclusion: "Performance is positive, but repeatability confidence is medium because gains are concentrated in a few favorable windows.",
    confidence: "Medium",
    positive: "Positive residual return and a stable NAV path in ordinary conditions.",
    risk: "A limited sample makes the forward return range unusually wide.",
    meaning: "Headline return deserves attention, but the uncertainty band matters more than the point estimate.",
    chart: "performance",
    metrics: metrics(
      ["Total return", "+18.4%", "High", "Observed net return"],
      ["Annualized return", "+39.1%", "Low", "Analytical estimate"],
      ["Volatility", "12.8%", "Medium", "Annualized"],
      ["Sharpe ratio", "1.62", "Medium", "6-month sample"],
      ["Positive return probability", "68%", "Medium", "Bootstrap estimate"],
      ["Return concentration", "34%", "Medium", "Top five windows"],
    ),
  },
  {
    id: "risk",
    shortLabel: "Risk",
    title: "Risk & Drawdowns",
    question: "What are the key risks and potential losses?",
    conclusion: "The main observed risk is tail behavior during sharp market moves, rather than ordinary day-to-day volatility.",
    confidence: "Medium",
    positive: "Most drawdowns recovered within twelve days.",
    risk: "Short-gamma behavior can accelerate losses during abrupt moves.",
    meaning: "The strategy should be judged by its tail-loss potential and recovery behavior, not only average volatility.",
    chart: "risk",
    metrics: metrics(
      ["Max drawdown", "-11.8%", "High", "Observed"],
      ["Current drawdown", "-2.4%", "High", "As of 30 May"],
      ["Recovery time", "19 days", "Medium", "Longest recovery"],
      ["Worst 1d loss", "-5.7%", "High", "Observed"],
      ["VaR 95%", "-2.8%", "Medium", "Daily estimate"],
      ["P(drawdown < -10%)", "14%", "Low", "Bootstrap estimate"],
    ),
  },
  {
    id: "pnl",
    shortLabel: "PnL",
    title: "PnL Distribution & Path Dependency",
    question: "What drives the strategy's profits and losses?",
    conclusion: "Frequent small gains are offset by rarer, larger losses; post-loss recovery exists but is not yet a stable edge.",
    confidence: "Medium",
    positive: "A 64% win frequency produces a steady ordinary-regime profile.",
    risk: "Negative skew and clustered losses reveal meaningful path dependency.",
    meaning: "A high win rate should not be mistaken for low risk because the loss tail is materially larger.",
    chart: "distribution",
    metrics: metrics(
      ["Win frequency", "64%", "High", "4h observations"],
      ["Median win", "+0.31%", "High", "Observed"],
      ["Median loss", "-0.47%", "High", "Observed"],
      ["Payoff ratio", "0.66", "High", "Median win / loss"],
      ["Skewness", "-1.34", "Medium", "Negative tail"],
      ["Top PnL concentration", "29%", "Medium", "Best five periods"],
    ),
  },
  {
    id: "regime",
    shortLabel: "Regimes",
    title: "Market Regime & Exposure",
    question: "When does the strategy perform best?",
    conclusion: "The strategy appears strongest in flat and low-to-moderate volatility regimes; bear-market behavior is not sufficiently evidenced.",
    confidence: "Medium",
    positive: "Residual performance remains positive when broad markets are flat.",
    risk: "High-volatility and bear-market coverage is limited.",
    meaning: "The strategy may diversify ordinary markets, but its behavior in stressed regimes remains uncertain.",
    chart: "regime",
    metrics: metrics(
      ["Flat market return", "+9.2%", "Medium", "62 observations"],
      ["High-vol return", "-4.8%", "Low", "21 observations"],
      ["Best regime", "Low volatility", "Medium", "Sharpe 2.1"],
      ["BTC correlation", "0.18", "Medium", "Rolling 30d"],
      ["Residual Sharpe", "1.24", "Medium", "After benchmark"],
      ["Diversification score", "71 / 100", "Medium", "Cross-market estimate"],
    ),
  },
  {
    id: "dna",
    shortLabel: "Strategy DNA",
    title: "Strategy DNA & Edge",
    question: "What drives the strategy's edge?",
    conclusion: "Short gamma is likely: negative convexity, weaker PnL during large moves and negative skew point to a carry-driven edge.",
    confidence: "Medium",
    positive: "Low market beta and positive residual alpha support a distinct return source.",
    risk: "Tail risk and execution sensitivity can dominate the carry edge.",
    meaning: "The apparent edge is compensation for absorbing volatility risk, not a free-standing source of return.",
    chart: "dna",
    metrics: metrics(
      ["Short gamma", "Likely", "Medium", "Convexity proxy"],
      ["Residual alpha", "+8.1%", "Medium", "Annualized estimate"],
      ["Market beta", "0.14", "Medium", "Main benchmark"],
      ["Tail risk", "High", "Medium", "Negative skew"],
      ["Execution sensitivity", "Moderate", "Medium", "Slippage stress"],
      ["Systematic profile", "Likely", "Low", "Rule consistency"],
    ),
  },
  {
    id: "sizing",
    shortLabel: "Sizing",
    title: "Trading Rules & Position Sizing",
    question: "How can this strategy be used more effectively?",
    conclusion: "Full Kelly is too aggressive for the observed confidence level; fractional sizing is more appropriate for analytical monitoring.",
    confidence: "Low",
    positive: "Expected value remains positive across a moderate sizing range.",
    risk: "Estimates degrade quickly when confidence and tail-risk adjustments are applied.",
    meaning: "This is an analytical estimate, not financial advice. Sizing conclusions require a longer and broader sample.",
    chart: "sizing",
    metrics: metrics(
      ["Expected value", "+0.08%", "Medium", "Per 4h period"],
      ["Full Kelly", "24%", "Low", "Unadjusted estimate"],
      ["Fractional Kelly", "6%", "Low", "Quarter Kelly"],
      ["Confidence-adjusted size", "3.5%", "Low", "Analytical estimate"],
      ["Entry timing score", "58 / 100", "Low", "Current condition"],
      ["Post-loss entry edge", "+0.11%", "Low", "Small sample"],
    ),
  },
  {
    id: "capacity",
    shortLabel: "Readiness",
    title: "Capacity, Execution & Allocation Readiness",
    question: "Is this strategy ready to scale?",
    conclusion: "Convexity Harvest merits further due diligence, not blind allocation based on headline returns.",
    confidence: "Medium",
    positive: "Evidence of an edge is promising in flat and low-to-moderate volatility regimes.",
    risk: "Short-gamma exposure and limited regime coverage require continued monitoring.",
    meaning: "The current status is Further Due Diligence. Capacity and execution remain acceptable at the tracked scale.",
    chart: "capacity",
    metrics: metrics(
      ["Tracked capital", "$4.2m", "High", "Connected accounts"],
      ["Practical capacity", "$18m", "Low", "Analytical estimate"],
      ["Fee drag", "2.1%", "Medium", "Annualized"],
      ["Slippage sensitivity", "Moderate", "Medium", "Stress tested"],
      ["Margin buffer", "31%", "Medium", "Observed median"],
      ["Final readiness", "Further Due Diligence", "Medium", "Not investment advice"],
    ),
  },
  {
    id: "evidence",
    shortLabel: "Evidence",
    title: "Evidence & Confidence",
    question: "Can I trust the data behind this strategy?",
    conclusion: "Data quality supports preliminary due diligence, but the short track record limits confidence across market regimes.",
    confidence: "Medium",
    positive: "NAV reconstruction and source freshness are consistently strong.",
    risk: "Transaction coverage is partial and no full crisis period is observed.",
    meaning: "The evidence is useful for continued analysis, but not yet broad enough for a high-confidence allocation decision.",
    chart: "verification",
    metrics: metrics(
      ["Verification score", "82 / 100", "High", "6-month audit window"],
      ["Observations", "1,086", "High", "4h intervals"],
      ["Missing data", "1.8%", "Medium", "20 intervals"],
      ["Source coverage", "91%", "Medium", "Account + transactions"],
      ["NAV reconstruction", "Complete", "High", "Independently rebuilt"],
      ["Manual edit risk", "Low", "High", "Source-protected data"],
    ),
  },
];

export const strategyReports: Record<string, StrategyReport> = {
  "convexity-harvest": {
    slug: "convexity-harvest",
    name: "Convexity Harvest",
    type: "Options Volatility / Short Volatility",
    market: "Global Derivatives",
    trackRecord: "6 months",
    granularity: "4h",
    lastUpdate: "30 May 2026",
    verificationScore: 82,
    riskLevel: "Moderate-High",
    readiness: "Further Due Diligence",
    confidence: "Medium",
    sections,
  },
};

export const chartData = {
  verification: [
    { name: "Source quality", value: 94 }, { name: "NAV rebuild", value: 91 },
    { name: "Transactions", value: 72 }, { name: "Freshness", value: 96 },
    { name: "Edit protection", value: 88 }, { name: "Completeness", value: 84 },
  ],
  performance: [
    { name: "Dec", nav: 100, low: 100, high: 100 }, { name: "Jan", nav: 103, low: 101, high: 105 },
    { name: "Feb", nav: 107, low: 103, high: 111 }, { name: "Mar", nav: 105, low: 99, high: 113 },
    { name: "Apr", nav: 114, low: 104, high: 121 }, { name: "May", nav: 118, low: 103, high: 130 },
    { name: "Jul*", nav: null, low: 98, high: 141 }, { name: "Sep*", nav: null, low: 92, high: 153 },
  ],
  risk: [
    { name: "Dec", value: 0 }, { name: "Jan", value: -2.1 }, { name: "Feb", value: -0.8 },
    { name: "Mar", value: -11.8 }, { name: "Apr", value: -3.4 }, { name: "May", value: -2.4 },
  ],
  distribution: [
    { name: "<-3%", value: 3 }, { name: "-3/-1%", value: 12 }, { name: "-1/0%", value: 25 },
    { name: "0/1%", value: 46 }, { name: "1/3%", value: 20 }, { name: ">3%", value: 5 },
  ],
  regime: [
    { name: "Bull", return: 6.4, drawdown: -4.1, confidence: 68 },
    { name: "Bear", return: -3.8, drawdown: -11.8, confidence: 38 },
    { name: "Flat", return: 9.2, drawdown: -2.9, confidence: 79 },
    { name: "High vol", return: -4.8, drawdown: -9.4, confidence: 42 },
    { name: "Low vol", return: 11.1, drawdown: -2.1, confidence: 82 },
  ],
  dna: [
    { subject: "Market beta", value: 24 }, { subject: "Residual alpha", value: 71 },
    { subject: "Trend", value: 31 }, { subject: "Mean reversion", value: 62 },
    { subject: "Short gamma", value: 84 }, { subject: "Tail risk", value: 78 },
    { subject: "Diversification", value: 67 }, { subject: "Execution", value: 58 },
  ],
  gamma: [
    { move: -8, pnl: -6.8 }, { move: -6, pnl: -3.9 }, { move: -4, pnl: -1.2 },
    { move: -2, pnl: 0.8 }, { move: 0, pnl: 1.3 }, { move: 2, pnl: 0.9 },
    { move: 4, pnl: -0.7 }, { move: 6, pnl: -3.2 }, { move: 8, pnl: -7.1 },
  ],
  sizing: [
    { name: "0%", growth: 0 }, { name: "3.5%", growth: 4.2 }, { name: "6%", growth: 5.5 },
    { name: "12%", growth: 6.1 }, { name: "24%", growth: 3.4 }, { name: "32%", growth: -2.8 },
  ],
  capacity: [
    { name: "$1m", return: 18.4 }, { name: "$4m", return: 17.8 }, { name: "$8m", return: 16.2 },
    { name: "$12m", return: 14.1 }, { name: "$18m", return: 10.8 }, { name: "$25m", return: 5.9 },
  ],
};
